### ISSUE TITLE
pas de mailto, on doit pouvoir copier le texte

### ISSUE THREAD

**Issue by squirelo** [HackerLoop/hackerloop-new-site#1]

**Comment by tchret** [comment]
à la mano? ou une feature copy to clipboard?

**Comment by squirelo** [comment]
faut que je reflechisse au mobile d'abord aussi pour ca, je vais looker quelques articles voir c'est quoi la best practice , on en parle demain , je pourrai le faire au pire

**Comment by squirelo** [comment]
https://blog.seibert-media.com/2014/10/06/why-mailto-links-should-be-avoided-on-websites/

**Comment by tchret** [comment]
fixed by #8
