### ISSUE TITLE
last rush

### ISSUE THREAD

**Issue by squirelo** [HackerLoop/hackerloop-new-site#7]
- repasser le header en video showreel qui prend la largeur, pour gagner de l'espace et alléger
- reduire de moitié les padding haut et bas des slices
- bouton messenger = contact us on messenger
- email doit etre en plain text sans bouton
- enlever toute animation en dehors du thumbnail pour l'instant, pas de tilt sur le thumbnail
- NEW --> rajouter Paris, Berlin & TallinN, a coté du bouton messenger et de l'email dans le header

**Comment by tchret** [comment]
fixed by #11
